const ACCOUNTING_ROLES = {
  CASH: 'CASH',
  BANK_CC: 'BANK_CC',
  BANK_SAVING: 'BANK_SAVING',
  SHARE: 'SHARE',
  COMPULSORY_DEPOSIT: 'COMPULSORY_DEPOSIT',
  SPECIAL_DEPOSIT: 'SPECIAL_DEPOSIT',
  REGULAR_LOAN: 'REGULAR_LOAN',
  LOAN_AGAINST_DEPOSIT: 'LOAN_AGAINST_DEPOSIT',
  ADMISSION: 'ADMISSION',
  PREMIUM: 'PREMIUM',
  SUSPENSE: 'SUSPENSE',
  EMPLOYEE_ADVANCE: 'EMPLOYEE_ADVANCE', // fallback
  EMPLOYEE_HOUSING_LOAN: 'EMPLOYEE_HOUSING_LOAN',
  EMPLOYEE_VEHICLE_LOAN: 'EMPLOYEE_VEHICLE_LOAN',
  EMPLOYEE_GRAIN_ADVANCE: 'EMPLOYEE_GRAIN_ADVANCE',
  INTEREST_INCOME: 'INTEREST_INCOME',
  INTEREST_EXPENSE: 'INTEREST_EXPENSE'
};

const POSTING_STATUS = {
  PROVEN: 'PROVEN',
  BLOCKED_LEGACY_UNKNOWN: 'BLOCKED_LEGACY_UNKNOWN',
  BLOCKED_ACCOUNTANT_DECISION: 'BLOCKED_ACCOUNTANT_DECISION',
  UNSUPPORTED: 'UNSUPPORTED'
};

module.exports = {
  ACCOUNTING_ROLES,
  POSTING_STATUS
};
