$ErrorActionPreference = 'Stop'

# bank transaction utils
$path = 'frontend/src/pages/transactions/bank/transactionUtils.js'
$content = Get-Content -Raw $path
$content = $content.Replace("export function createEmptyTransactionDraft(sectionKey = '', sectionItems = []) {", "export function createEmptyTransactionDraft(sectionKey = '', sectionItems = [], activeKey = '') {")
$content = $content.Replace("  const firstItem = sectionItems[0] || null;", "  const firstItem = getSectionItemByKey(sectionItems, activeKey) || sectionItems[0] || null;")
$content = $content.Replace("export function createTransactionDraftFromRecord(record = {}, sectionItems = [], sectionKey = '') {", "export function createTransactionDraftFromRecord(record = {}, sectionItems = [], sectionKey = '', activeKey = '') {")
$content = $content.Replace("  const firstItem = getSectionItemByKey(sectionItems, details.key) || sectionItems[0] || null;", "  const firstItem = getSectionItemByKey(sectionItems, details.key || activeKey) || getSectionItemByKey(sectionItems, activeKey) || sectionItems[0] || null;")
$content = $content.Replace("    mode: record.mode || firstItem?.mode || '',", "    mode: record.mode || details.transferType || firstItem?.mode || '',")
$content = $content.Replace("export function getVoucherSectionItem(voucher = {}, sectionItems = []) {", "export function getVoucherSectionItem(voucher = {}, sectionItems = [], activeKey = '') {")
$content = $content.Replace("  const key = cleanText(voucher?.details?.key || '');", "  const key = cleanText(voucher?.details?.key || activeKey || '');")
$content = $content.Replace("export function filterTransactionRows(rows = [], sectionItems = []) {", "export function filterTransactionRows(rows = [], sectionItems = [], activeKey = '') {")
$content = $content.Replace("  const itemKeys = new Set((Array.isArray(sectionItems) ? sectionItems : []).map((item) => cleanText(item.key)));", "  const itemKeys = new Set((Array.isArray(sectionItems) ? sectionItems : []).map((item) => cleanText(item.key)));`r`n  const normalizedActiveKey = cleanText(activeKey).toLowerCase();`r`n  const activeItemLabel = normalizedActiveKey`r`n    ? cleanText((Array.isArray(sectionItems) ? sectionItems : []).find((item) => cleanText(item.key).toLowerCase() === normalizedActiveKey)?.label || '').toLowerCase()`r`n    : '';")
$content = $content.Replace("    const rowKey = cleanText(row?.details?.key || '');`r`n    if (rowKey && itemKeys.has(rowKey)) return true;", "    const rowKey = cleanText(row?.details?.key || row?.transactionKey || row?.sectionKey || '').toLowerCase();`r`n    if (normalizedActiveKey) {`r`n      if (rowKey) return rowKey === normalizedActiveKey;`r`n      return cleanText(row.voucherCategory).toLowerCase() === activeItemLabel;`r`n    }`r`n    if (rowKey && itemKeys.has(rowKey)) return true;")
$content = $content.Replace("export function getTransactionVoucherTitle(voucher = {}, sectionItems = []) {", "export function getTransactionVoucherTitle(voucher = {}, sectionItems = [], activeKey = '') {")
$content = $content.Replace("  const item = getVoucherSectionItem(voucher, sectionItems);", "  const item = getVoucherSectionItem(voucher, sectionItems, activeKey);")
Set-Content -Path $path -Value $content

# bank index
$path = 'frontend/src/pages/transactions/bank/index.jsx'
$content = Get-Content -Raw $path
$content = $content.Replace("import { BankTransactionForm } from './form';", "import { BankTransactionForm } from './form';`r`nimport { getBankTransactionTypeByKey } from './bankConfig';")
$content = $content.Replace("export function BankTransactionsPage({ sectionKey, detailPathBase }) {", "export function BankTransactionsPage({ sectionKey, detailPathBase, itemKey = '' }) {")
$content = $content.Replace("  const section = useMemo(() => catalog.find((item) => item.key === sectionKey) || null, [catalog, sectionKey]);`r`n  const sectionItems = useMemo(() => getSectionItems(catalog, sectionKey), [catalog, sectionKey]);`r`n  const visibleRows = useMemo(() => {`r`n    const baseRows = filterTransactionRows(rows, sectionItems);", "  const section = useMemo(() => catalog.find((item) => item.key === sectionKey) || null, [catalog, sectionKey]);`r`n  const sectionItems = useMemo(() => getSectionItems(catalog, sectionKey), [catalog, sectionKey]);`r`n  const activeItem = useMemo(() => getBankTransactionTypeByKey(itemKey), [itemKey]);`r`n  const activeSectionItems = useMemo(() => (activeItem ? sectionItems.filter((entry) => entry.key === activeItem.key) : sectionItems), [activeItem, sectionItems]);`r`n  const currentItemKey = activeItem?.key || '';`r`n  const visibleRows = useMemo(() => {`r`n    const baseRows = filterTransactionRows(rows, activeSectionItems, currentItemKey);")
$content = $content.Replace("  }, [rows, sectionItems, search, filterStatus, filterPartyType, filterDateFrom, filterDateTo]);", "  }, [rows, activeSectionItems, currentItemKey, search, filterStatus, filterPartyType, filterDateFrom, filterDateTo]);")
$content = $content.Replace("    const item = sectionItems.find((entry) => entry.key === itemKey) || sectionItems[0] || null;", "    const key = itemKey || currentItemKey || activeSectionItems[0]?.key || '';`r`n    const item = activeSectionItems.find((entry) => entry.key === key) || activeSectionItems[0] || null;")
$content = $content.Replace("      const next = createEmptyTransactionDraft(sectionKey, sectionItems);", "      const next = createEmptyTransactionDraft(sectionKey, activeSectionItems, key);")
$content = $content.Replace("        details: { ...(next.details || {}), key: item?.key || next.details?.key || '' },", "        details: { ...(next.details || {}), key: item?.key || next.details?.key || key || '' },")
$content = $content.Replace("    setDraft(createTransactionDraftFromRecord(record, sectionItems, sectionKey));", "    setDraft(createTransactionDraftFromRecord(record, activeSectionItems, sectionKey, currentItemKey));")
$content = $content.Replace("    setDraft(createEmptyTransactionDraft(sectionKey, sectionItems));", "    setDraft(createEmptyTransactionDraft(sectionKey, activeSectionItems, currentItemKey));")
$content = $content.Replace("  const linkedItems = useMemo(() => (sectionItems || []).filter((item) => item.route), [sectionItems]);`r`n  const editableItems = useMemo(() => (sectionItems || []).filter((item) => !item.route), [sectionItems]);", "  const linkedItems = useMemo(() => (activeSectionItems || []).filter((item) => item.route), [activeSectionItems]);`r`n  const editableItems = useMemo(() => (activeSectionItems || []).filter((item) => !item.route), [activeSectionItems]);")
$content = $content.Replace("          <h1 className=\"mt-2 text-2xl font-semibold tracking-tight text-slate-900\">{section?.label || sectionKey} Transactions</h1>", "          <p className=\"text-[12px] font-semibold uppercase tracking-[0.22em] text-[var(--primary)]\">Bank Transactions</p>`r`n          <h1 className=\"mt-2 text-2xl font-semibold tracking-tight text-slate-900\">{activeItem?.label || section?.label || sectionKey} Transactions</h1>")
$content = $content.Replace("              Create Transaction", "              {activeItem ? `Create ${activeItem.label}` : 'Create Transaction'}")
$content = $content.Replace("      sortValue: (row) => getTransactionVoucherTitle(row, sectionItems),", "      sortValue: (row) => getTransactionVoucherTitle(row, activeSectionItems, currentItemKey),")
$content = $content.Replace("      render: (row) => <span className=\"text-slate-700\">{getTransactionVoucherTitle(row, sectionItems)}</span>", "      render: (row) => <span className=\"text-slate-700\">{getTransactionVoucherTitle(row, activeSectionItems, currentItemKey)}</span>")
$content = $content.Replace("        title={activeRecord ? `Edit ${draft?.voucherCategory || 'Transaction'}` : `Create ${draft?.voucherCategory || 'Transaction'}`}", "        title={activeRecord ? `Edit ${draft?.voucherCategory || activeItem?.label || 'Transaction'}` : `Create ${draft?.voucherCategory || activeItem?.label || 'Transaction'}`}")
$content = $content.Replace("              {saving ? 'Saving...' : (activeRecord ? 'Save Changes' : `Create ${draft?.voucherCategory || 'Transaction'}`)}", "              {saving ? 'Saving...' : (activeRecord ? 'Save Changes' : `Create ${draft?.voucherCategory || activeItem?.label || 'Transaction'}`)}")
Set-Content -Path $path -Value $content

# bank detail
$path = 'frontend/src/pages/transactions/bank/detail.jsx'
$content = Get-Content -Raw $path
$content = $content.Replace("export function BankTransactionDetailPage({ sectionKey }) {", "export function BankTransactionDetailPage({ sectionKey, itemKey = '', detailPathBase = '/app/transactions/bank' }) {")
$content = $content.Replace("  const section = useMemo(() => catalog.find((item) => item.key === sectionKey) || null, [catalog, sectionKey]);`r`n  const sectionItems = useMemo(() => getSectionItems(catalog, sectionKey), [catalog, sectionKey]);", "  const section = useMemo(() => catalog.find((item) => item.key === sectionKey) || null, [catalog, sectionKey]);`r`n  const sectionItems = useMemo(() => getSectionItems(catalog, sectionKey), [catalog, sectionKey]);`r`n  const activeItem = useMemo(() => sectionItems.find((item) => item.key === itemKey) || null, [sectionItems, itemKey]);")
$content = $content.Replace("    setDraft(createTransactionDraftFromRecord(record, sectionItems, sectionKey));", "    setDraft(createTransactionDraftFromRecord(record, sectionItems, sectionKey, itemKey));")
$content = $content.Replace("      navigate(`/app/transactions/${sectionKey}`);", "      navigate(detailPathBase);")
$content = $content.Replace("  const title = getTransactionVoucherTitle(record, sectionItems);", "  const title = getTransactionVoucherTitle(record, sectionItems, itemKey);")
$content = $content.Replace("  const templateItem = getVoucherSectionItem(record, sectionItems);", "  const templateItem = getVoucherSectionItem(record, sectionItems, itemKey);")
$content = $content.Replace("        <button type=\"button\" onClick={() => navigate(`/app/transactions/${sectionKey}`)} className=\"flex items-center gap-1.5 transition-colors hover:text-slate-900\">", "        <button type=\"button\" onClick={() => navigate(detailPathBase)} className=\"flex items-center gap-1.5 transition-colors hover:text-slate-900\">")
$content = $content.Replace("                  {record.voucherNo || 'Voucher Detail'}", "                  {record.voucherNo || (activeItem?.label || 'Voucher Detail')}")
$content = $content.Replace("                <span className=\"text-slate-900\">{section?.label || sectionKey} Detail</span>", "                <span className=\"text-slate-900\">{activeItem?.label || section?.label || sectionKey} Detail</span>")
$content = $content.Replace("  const documentDefs = getBankDocumentDefinitions(templateItem?.key || record?.details?.key || '');", "  const documentDefs = getBankDocumentDefinitions(templateItem?.key || record?.details?.key || itemKey || '');")
Set-Content -Path $path -Value $content
